apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcafe-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcafe-backend
  template:
    metadata:
      labels:
        app: webcafe-backend
    spec:
      containers:
      - name: backend
        image: ducsmanh/backend-webcafe:latest 
        ports:
        - containerPort: 8080