apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcafe-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcafe-backend
  template:
    metadata:
      labels:
        app: webcafe-backend
    spec:
      containers:
      - name: backend
        image: ducsmanh/backend-webcafe:latest 
        ports:
        - containerPort: 8080
```
Lưu file (`Ctrl+O`, `Enter`, `Ctrl+X`).

### 3. Tạo file `frontend-deployment.yml`

```bash
nano frontend-deployment.yml