apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcafe-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcafe-backend
  template:
    metadata:
      labels:
        app: webcafe-backend
        release: prometheus 
      annotations: 
        prometheus.io/scrape: "true" 
        prometheus.io/path: "/actuator/prometheus" 
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: backend
        image: ducsmanh/backend-webcafe:latest 
        ports:
        - containerPort: 8080