apiVersion: v1
kind: Service
metadata:
  name: webcafe-backend-service
spec:
  selector:
    app: webcafe-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webcafe-frontend-service
spec:
  type: LoadBalancer 
  selector:
    app: webcafe-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80